apiVersion: v1
kind: Service
metadata:
  name: {{ include "oci-webhook.fullname" . }}
  labels:
    app: {{ include "oci-webhook.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "oci-webhook.name" . }}
    release: {{ .Release.Name }}
