---
# Source: oci-webhook/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-oci-webhook
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
---
# Source: oci-webhook/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-oci-webhook:domain-solver
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
rules:
  - apiGroups:
      - alexgl.fr
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: oci-webhook/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-oci-webhook:auth-delegator
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-oci-webhook
    namespace: argocd
---
# Source: oci-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-oci-webhook:domain-solver
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-oci-webhook:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: oci-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-oci-webhook:secret-reader
  namespace: argocd
rules:
  - apiGroups:
    - ""
    resources: 
    - "secrets"
    verbs:
    - "get"
    - "watch"
---
# Source: oci-webhook/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-oci-webhook:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-oci-webhook
    namespace: argocd
---
# Source: oci-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-oci-webhook:secret-reader
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-oci-webhook:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-oci-webhook
    namespace: argocd
---
# Source: oci-webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-oci-webhook
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: oci-webhook
    release: cert-manager-oci-webhook
---
# Source: oci-webhook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-oci-webhook
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oci-webhook
      release: cert-manager-oci-webhook
  template:
    metadata:
      labels:
        app: oci-webhook
        release: cert-manager-oci-webhook
    spec:
      serviceAccountName: cert-manager-oci-webhook
      containers:
        - name: oci-webhook
          image: "ghcr.io/alexandre-gl/cert-manager-oci-webhook:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "alexgl.fr"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-oci-webhook-webhook-tls
---
# Source: oci-webhook/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.alexgl.fr
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "argocd/cert-manager-oci-webhook-webhook-tls"
spec:
  group: alexgl.fr
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-oci-webhook
    namespace: argocd
  version: v1alpha1
---
# Source: oci-webhook/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-oci-webhook-ca
  namespace: "argocd"
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
spec:
  secretName: cert-manager-oci-webhook-ca
  duration: 43800h # 5y
  issuerRef:
    name: cert-manager-oci-webhook-selfsign
  commonName: "ca.oci-webhook.cert-manager"
  isCA: true
---
# Source: oci-webhook/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-oci-webhook-webhook-tls
  namespace: "argocd"
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
spec:
  secretName: cert-manager-oci-webhook-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-oci-webhook-ca
  dnsNames:
  - cert-manager-oci-webhook
  - cert-manager-oci-webhook.argocd
  - cert-manager-oci-webhook.argocd.svc
---
# Source: oci-webhook/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-oci-webhook-selfsign
  namespace: "argocd"
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: oci-webhook/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-oci-webhook-ca
  namespace: "argocd"
  labels:
    app: oci-webhook
    chart: oci-webhook-0.1.0
    release: cert-manager-oci-webhook
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-oci-webhook-ca
